export const C = {
  bg: '#fcf8fa',
  surface: '#ffffff',
  surfaceContainer: '#f0edee',
  surfaceContainerLow: '#f6f3f4',
  surfaceContainerHigh: '#ebe7e9',
  outline: '#767686',
  outlineVariant: '#c6c5d7',
  primary: '#3d4ad8',
  primaryContainer: '#5865f2',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#fffdff',
  onBg: '#1c1b1d',
  onSurface: '#1c1b1d',
  onSurfaceVariant: '#454655',
  secondary: '#5c5f60',
  secondaryContainer: '#dee0e2',
  error: '#ba1a1a',
  green: '#22c55e',
} as const;
